IRSR24-28 | @jdwjdwjdw | Add search button to nav
SU-SWS/ppo_irsr_subtheme pull request #10
Opened 2023-11-09 19:50 UTC by jdwjdwjdw

# NOT READY FOR REVIEW

# Summary
- [IRSR24-28](https://stanfordits.atlassian.net/browse/IRSR24-28): Search in Navigation

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Urgency
- How urgent is this? (Normal, High)

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Navigate to...
4. Verify...

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory?

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

## Backend / Functional Validation
### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

2023-11-16 22:04 UTC, rebeccahongsf commented on src/scss/components/search/_search.scss
> +      width: 2.6rem;
The search icon appears a bit bigger than the neighboring text

![image](https://github.com/SU-SWS/ppo_irsr_subtheme/assets/34019925/22387815-15c1-442f-a8d4-e447d326cc47)

Would you be able to update the sizing to match the figma mock? 😃 

![image](https://github.com/SU-SWS/ppo_irsr_subtheme/assets/34019925/999e6731-c927-430a-a482-9b9b6a5cc00c)

2023-11-16 22:05 UTC, rebeccahongsf commented on src/js/ppo_irsr_subtheme.behaviors.js
> +      $('.su-multi-menu', context).append(menuSearchButton);
Is there a way we can add the search icon here instead of a background image?

2023-11-17 20:06 UTC, jdwjdwjdw commented
Thanks @rebeccahongsf! I decided to take your suggestion and update the search icon to using font awesome, as my previous solution didn't display in situations where images are disabled. The sizing should now better match figma, and I updated the color to match figma as well (you'll see that it's using `$su-color-cardinal-red-dark`, so slightly darker than the links). Let me know if you see any further adjustments needed!

2023-11-17 23:35 UTC, rebeccahongsf requested changes
Thank you for implementing the changes @jdwjdwjdw 😃 It looks great to me on desktop!
![image](https://github.com/SU-SWS/ppo_irsr_subtheme/assets/34019925/ddd235a4-dabd-4581-ad42-53b6698a3aef)

I did notice that the search button appears on mobile
![image](https://github.com/SU-SWS/ppo_irsr_subtheme/assets/34019925/47dd1ab0-cac2-4cf6-8382-3d132910a619)

Once that's updated, we should be good to go!

2023-11-17 23:35 UTC, rebeccahongsf commented on src/scss/components/search/_search.scss
> +  .menu-search-button {
```suggestion
  .menu-search-link {
```
Just gotta update this to the correct target class and we should be good to go! 😄

2023-11-17 23:57 UTC, jdwjdwjdw commented
Good catch @rebeccahongsf! Updated and should be good to go now.

2023-11-18 01:00 UTC, rebeccahongsf approved these changes
Everything looks awesome! Thank you @jdwjdwjdw 🚢

2023-11-18 01:06 UTC, merged