IRSR24-16 | @jdwjdwjdw | Update lists and teasers to align with h1
SU-SWS/ppo_irsr_subtheme pull request #8
Opened 2023-10-18 19:41 UTC by jdwjdwjdw

# NOT READY FOR REVIEW

# Summary
- [IRSR24-16](https://stanfordits.atlassian.net/browse/IRSR24-16): H1 left-aligned with cards
  - Achieved this by updating the max-width of teasers and lists
  - Works for layout `None` pages and layout `Full Width` pages.

# Review By (Date)
- When convenient

# Urgency
- Normal

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Navigate to...
4. Verify...

# Associated Issues and/or People
- [IRSR24-16](https://stanfordits.atlassian.net/browse/IRSR24-16): H1 left-aligned with cards

[IRSR24-16]: https://stanfordits.atlassian.net/browse/IRSR24-16?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-10-23 20:20 UTC, rebeccahongsf approved these changes
LGTM 🚀

2023-10-23 20:33 UTC, rebeccahongsf requested changes
I was reviewing the code and realize that your styles were targeting `.layout--layout-paragraphs-one-column` for the full width. 

Is the goal to have the heading align with the start of the card/teaser in one column? 🤔 

When there are multiple items in the row, the first one aligns with the No Layout but doesn't align with the Full Width.

<img width="1512" alt="image" src="https://github.com/SU-SWS/ppo_irsr_subtheme/assets/34019925/fec3d873-65be-4895-ad2f-b30704c2ab93">

<img width="1512" alt="image" src="https://github.com/SU-SWS/ppo_irsr_subtheme/assets/34019925/c9dae224-68af-479b-872e-c21080ba006f">

<img width="1247" alt="image" src="https://github.com/SU-SWS/ppo_irsr_subtheme/assets/34019925/ffb7a734-bca8-460a-baf9-2426ce3211dc">

<img width="1512" alt="image" src="https://github.com/SU-SWS/ppo_irsr_subtheme/assets/34019925/9b288a43-6a2f-48a6-8a03-fe419197fbec">

Edit: Added missing screenie for No Layout :D

2023-10-24 18:38 UTC, jdwjdwjdw commented
@rebeccahongsf thanks for pointing that out! I made some adjustments to the two and three column layouts for full-width pages which should make things look more consistent. Let me know what you think.

2023-10-24 22:14 UTC, rebeccahongsf approved these changes
@jdwjdwjdw it's looking great now! Thank you for the speedy turnaround.

What you have totally works but I left a styling comment in case you wanted to use the [`responsive-flex-column()`](https://decanter.stanford.edu/docs/scss/index.html#mixin-mixin-responsive-flex-column) mixin instead of css. This mixin matches the `flex-10-of-12` class in one of the wrappers for the h1 😃

2023-10-24 22:14 UTC, rebeccahongsf commented on src/scss/basic-page/full-width.scss
> +    }
```suggestion
    @include responsive-flex-column(10);
```

2023-10-24 22:14 UTC, rebeccahongsf commented on src/scss/basic-page/full-width.scss
> +    }
```suggestion
    @include responsive-flex-column(10);
```

2023-10-24 23:35 UTC, jdwjdwjdw commented
Thanks for bringing up that mixin @rebeccahongsf ! I added your suggestions. Makes ever thing much cleaner 🎉

2023-10-24 23:36 UTC, merged